---

- name: chekout musicbrainz-server repository
  git: repo={{ musicbrainz_git_repository }}
       dest={{ musicbrainz_install_directory }}
       version={{ musicbrainz_git_version }}
       depth=1
       accept_hostkey=yes
       force=yes
  register: musicbrainz_repository


- name: add DBDefs.pm config file
  template: src=files/DBDefs-slave.pm
            dest={{ musicbrainz_install_directory }}/lib/DBDefs.pm

- name: enable local::lib in ~/.bashrc
  lineinfile: dest=~/.bashrc line="eval $( perl -Mlocal::lib )"

# cpanm task initially takes ~20 minutes
- name: install dependencies (cpanm)
  command: >
    cpanm --installdeps --notest .
    chdir={{ musicbrainz_install_directory }}
  when: musicbrainz_repository.changed

# npm task initially takes ~10 minutes
- name: install dependencies (npm)
  command: >
    npm install
    chdir={{ musicbrainz_install_directory }}
  when: musicbrainz_repository.changed

- name: compile assets (npm/gulp)
  command: >
    ./script/compile_resources.sh
    chdir={{ musicbrainz_install_directory }}
  when: musicbrainz_repository.changed

##
# build additional postgres tools
- name: build postgresql-musicbrainz-unaccent
  command: >
    make
    chdir={{ musicbrainz_install_directory }}/postgresql-musicbrainz-unaccent
  when: musicbrainz_repository.changed

- name: install postgresql-musicbrainz-unaccent
  command: >
    make install
    chdir={{ musicbrainz_install_directory }}/postgresql-musicbrainz-unaccent
  when: musicbrainz_repository.changed

- name: build postgresql-musicbrainz-collate
  command: >
    make
    chdir={{ musicbrainz_install_directory }}/postgresql-musicbrainz-collate
  when: musicbrainz_repository.changed

- name: install postgresql-musicbrainz-collate
  command: >
    make install
    chdir={{ musicbrainz_install_directory }}/postgresql-musicbrainz-collate
  when: musicbrainz_repository.changed

##
# configure postgresql access
# NOTE: there are no special security measurements in place. (local   all    all    trust)
# in the default setup the system is considered to run on an isolated instance in a vpn environment with local
# network only - and http() access via reverse proxy.
# further there is no sensitive information in the database (only the public mb dump) - so we consider this as
# save enough.
- name: add pg_hba.conf config file
  template: src=files/pg_hba.conf
            dest=/etc/postgresql/9.5/main/pg_hba.conf

- name: restart postgresql service
  service: name=postgresql state=restarted

