---

# Get latest available dump
#  radds {{ musicbrainz_dump_mirror }}LATEST
#  and check for the latest available version
- name: get latest dump key
  action: uri url={{ musicbrainz_dump_mirror | replace('ftp://', 'http://') }}LATEST return_content=yes
  register: latest_key

- name: set dump base path
  set_fact:
    musicbrainz_dump_base_url: "{{ musicbrainz_dump_mirror }}{{ latest_key.content | replace('\n', '') }}/"
    musicbrainz_dump_base_dir: "{{ musicbrainz_dump_directory }}{{ latest_key.content  | replace('\n', '') }}/"

- name: ensure dump directory is available
  file: path={{ musicbrainz_dump_base_dir }} state=directory

# TODO: inestigate download. Does not work through ansible (both ftp & http)
# Bug: https://github.com/ansible/ansible-modules-core/issues/3661
# Current workaround: wget dumps manuallly :(
- name: download dump files if not present
  get_url: url={{ musicbrainz_dump_base_url | replace('ftp://', 'http://') }}{{ item }} dest={{ musicbrainz_dump_base_dir }}{{ item }}
  with_items:
   - mbdump.tar.bz2
   - mbdump-editor.tar.bz2
   - mbdump-derived.tar.bz2
  #changed_when: False


- name: load initial db dumps (./admin/InitDb.pl)
  command: >
    ./admin/InitDb.pl --createdb --import {{ musicbrainz_dump_base_dir }}mbdump*.tar.bz2 --echo
    chdir={{ musicbrainz_install_directory }}
